### ISSUE TITLE
Use Webhooks to trigger CentOS CI Jobs

### ISSUE THREAD

**Issue by bstinsonmhk** [sclorg/rhscl-container-ci#13]
Hi Folks,

We need to use github webhooks to trigger jobs in CentOS CI. Currently we're polling the whole sclorg organization, and exhausting our API quota.

We need the hooks added like in Mode 2 described here:
https://wiki.centos.org/QaWiki/CI/GithubIntegration

And to set `github-hooks: true` in your github-pull-request trigger block

Until we get this worked out, I need to temporarily disable these jobs in CentOS CI.

**Comment by omron93** [comment]
@bstinsonmhk I suppose `cron` can't be set in github-pull-request trigger block, right?

**Comment by omron93** [comment]
@bstinsonmhk Also who can accept invitations for `centos-ci` user on github.com?

It was removed from sclorg so now it can't set github hooks ...

**Comment by bstinsonmhk** [comment]
You still need the cron line, because that says "How often should this job check to see if it's been triggered?" 

On the webhooks, we need to keep the centos-ci user out of organizations for now, joining an organization is very expensive in terms of API calls per hour. You can set webhooks manually using Mode 2 described here: https://wiki.centos.org/QaWiki/CI/GithubIntegration

**Comment by omron93** [comment]
> On the webhooks, we need to keep the centos-ci user out of organizations for now, joining an organization is very expensive in terms of API calls per hour

This is really unpleasant news. Without this maintaining of several repositories is harder. It was possible to use teams to maintain permissions to more repositories in one place, now for repository collaborator has to be added separately.

**Comment by praiskup** [comment]
@bstinsonmhk wrote:
> joining an organization is very expensive in terms of API calls per hour. 

Can you elaborate?  Except that we setup some web-hook (manually), what else generates API calls if you added centos-ci into sclorg group?

Said that, we don't want to over-flood the jenkins api quotas -- so we won't setup webhooks in repositories where it is useless.

**Comment by omron93** [comment]
Answer from kbsingh on #centos-devel

```
me:  for what are api calls used? (in case of being member of org)
kbs:  its used to find out all the team members and then the repos , and then associate one to the other
me: and this is done when checking if user can trigger build? Or when?
kbs: yeah, at time of pr or merge to master etc
       everytime there is an action
```

**Comment by phracek** [comment]
This is already fixed. https://github.com/sclorg/rhscl-container-ci/blob/old_jenkins/yaml/triggers/github-pr.yaml#L37

Closing it.

**Comment by phracek** [comment]
Soon we are moving into support fedmsg or Fedora Messaging.
