### ISSUE TITLE
Do not test latest version of dependent images if not available

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/rhscl-container-ci#14]
The CI tests should be a bit more clever about testing dependent images (as is in case of s2i-base). 

Currently only the latest version of the image is tested, regardless of whether it was actually built. The scripts should first check if it can be built (Dockerfile exists) and if not try an older version.

Related: https://github.com/sclorg/varnish-container/issues/31

**Comment by phracek** [comment]
This repo is not used at all. We used Testing Farm. Closing
